// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reportProblem.proto

package grpc.reportProblemService;

public interface emptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:empty)
    com.google.protobuf.MessageOrBuilder {
}
