// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reportProblem.proto

package grpc.reportProblemService;

public interface logoutRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:logoutRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string request = 1;</code>
   */
  java.lang.String getRequest();
  /**
   * <code>string request = 1;</code>
   */
  com.google.protobuf.ByteString
      getRequestBytes();
}
