// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reportProblem.proto

package grpc.reportProblemService;

public interface problemTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:problemType)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 number = 1;</code>
   */
  int getNumber();
}
