// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transport.proto

package TransportService;

public interface chatRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chatRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string request = 1;</code>
   */
  java.lang.String getRequest();
  /**
   * <code>string request = 1;</code>
   */
  com.google.protobuf.ByteString
      getRequestBytes();
}
