// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transport.proto

package TransportService;

public interface chatResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chatResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string reponse = 1;</code>
   */
  java.lang.String getReponse();
  /**
   * <code>string reponse = 1;</code>
   */
  com.google.protobuf.ByteString
      getReponseBytes();
}
