// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transport.proto

package TransportService;

public interface routeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:routeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string from = 1;</code>
   */
  java.lang.String getFrom();
  /**
   * <code>string from = 1;</code>
   */
  com.google.protobuf.ByteString
      getFromBytes();

  /**
   * <code>string destination = 2;</code>
   */
  java.lang.String getDestination();
  /**
   * <code>string destination = 2;</code>
   */
  com.google.protobuf.ByteString
      getDestinationBytes();
}
