// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transport.proto

package TransportService;

public interface routesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:routes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string response = 1;</code>
   */
  java.lang.String getResponse();
  /**
   * <code>string response = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponseBytes();
}
