// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transport.proto

package TransportService;

public final class TransportServiceImpl {
  private TransportServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_routeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_routeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_routes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_routes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transportType_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transportType_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_times_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_times_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chatResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chatResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017transport.proto\"1\n\014routeRequest\022\014\n\004fro" +
      "m\030\001 \001(\t\022\023\n\013destination\030\002 \001(\t\"\032\n\006routes\022\020" +
      "\n\010response\030\001 \001(\t\"i\n\rtransportType\022-\n\ntra" +
      "nsports\030\001 \001(\0162\031.transportType.Transports" +
      "\")\n\nTransports\022\010\n\004DART\020\000\022\007\n\003BUS\020\001\022\010\n\004LUA" +
      "S\020\002\"\025\n\005times\022\014\n\004time\030\001 \001(\t\"\036\n\013chatReques" +
      "t\022\017\n\007request\030\001 \001(\t\"\037\n\014chatResponse\022\017\n\007re" +
      "ponse\030\001 \001(\t2\221\001\n\020TransportService\022(\n\nEnte" +
      "rRoute\022\r.routeRequest\032\007.routes\"\0000\001\022(\n\nCh" +
      "eckTimes\022\016.transportType\032\006.times\"\0000\001\022)\n\004" +
      "Chat\022\014.chatRequest\032\r.chatResponse\"\000(\0010\001B" +
      "*\n\020TransportServiceB\024TransportServiceImp" +
      "lP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_routeRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_routeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_routeRequest_descriptor,
        new java.lang.String[] { "From", "Destination", });
    internal_static_routes_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_routes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_routes_descriptor,
        new java.lang.String[] { "Response", });
    internal_static_transportType_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_transportType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transportType_descriptor,
        new java.lang.String[] { "Transports", });
    internal_static_times_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_times_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_times_descriptor,
        new java.lang.String[] { "Time", });
    internal_static_chatRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_chatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chatRequest_descriptor,
        new java.lang.String[] { "Request", });
    internal_static_chatResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_chatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chatResponse_descriptor,
        new java.lang.String[] { "Reponse", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
