// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transport.proto

package TransportService;

public interface transportTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:transportType)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.transportType.Transports transports = 1;</code>
   */
  int getTransportsValue();
  /**
   * <code>.transportType.Transports transports = 1;</code>
   */
  TransportService.transportType.Transports getTransports();
}
