// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: charging_spots.proto

package ChargingSpotsService;

public interface chargingSpotsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chargingSpots)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string street = 1;</code>
   */
  java.lang.String getStreet();
  /**
   * <code>string street = 1;</code>
   */
  com.google.protobuf.ByteString
      getStreetBytes();

  /**
   * <code>string area = 2;</code>
   */
  java.lang.String getArea();
  /**
   * <code>string area = 2;</code>
   */
  com.google.protobuf.ByteString
      getAreaBytes();
}
