// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: charging_spots.proto

package ChargingSpotsService;

public final class ChargingSpotsServiceImpl {
  private ChargingSpotsServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coordinates_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coordinates_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chargingSpots_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chargingSpots_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_prices_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_prices_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_time_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_time_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_command_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_command_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024charging_spots.proto\"2\n\013coordinates\022\021\n" +
      "\tlongitude\030\001 \001(\001\022\020\n\010latitude\030\002 \001(\001\"-\n\rch" +
      "argingSpots\022\016\n\006street\030\001 \001(\t\022\014\n\004area\030\002 \001(" +
      "\t\"\027\n\006prices\022\r\n\005price\030\001 \001(\001\"\'\n\004time\022\016\n\006ti" +
      "meOn\030\001 \001(\001\022\017\n\007timeOff\030\002 \001(\001\"\032\n\007command\022\017" +
      "\n\007command\030\001 \001(\t2\230\001\n\024ChargingSpotsService" +
      "\0221\n\rTrackLocation\022\014.coordinates\032\016.chargi" +
      "ngSpots\"\000(\001\022*\n\013CheckPrices\022\016.chargingSpo" +
      "ts\032\007.prices\"\0000\001\022!\n\014AutomateTime\022\005.time\032\010" +
      ".command\"\000B2\n\024ChargingSpotsServiceB\030Char" +
      "gingSpotsServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_coordinates_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_coordinates_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coordinates_descriptor,
        new java.lang.String[] { "Longitude", "Latitude", });
    internal_static_chargingSpots_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_chargingSpots_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chargingSpots_descriptor,
        new java.lang.String[] { "Street", "Area", });
    internal_static_prices_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_prices_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_prices_descriptor,
        new java.lang.String[] { "Price", });
    internal_static_time_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_time_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_time_descriptor,
        new java.lang.String[] { "TimeOn", "TimeOff", });
    internal_static_command_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_command_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_command_descriptor,
        new java.lang.String[] { "Command", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
