// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: charging_spots.proto

package ChargingSpotsService;

public interface coordinatesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:coordinates)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double longitude = 1;</code>
   */
  double getLongitude();

  /**
   * <code>double latitude = 2;</code>
   */
  double getLatitude();
}
