// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: charging_spots.proto

package ChargingSpotsService;

public interface pricesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:prices)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double price = 1;</code>
   */
  double getPrice();
}
