// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: charging_spots.proto

package ChargingSpotsService;

public interface timeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:time)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double timeOn = 1;</code>
   */
  double getTimeOn();

  /**
   * <code>double timeOff = 2;</code>
   */
  double getTimeOff();
}
