// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: charging_spots.proto

package ChargingSpotsService;

/**
 * Protobuf type {@code time}
 */
public  final class time extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:time)
    timeOrBuilder {
private static final long serialVersionUID = 0L;
  // Use time.newBuilder() to construct.
  private time(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private time() {
    timeOn_ = 0D;
    timeOff_ = 0D;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private time(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 9: {

            timeOn_ = input.readDouble();
            break;
          }
          case 17: {

            timeOff_ = input.readDouble();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ChargingSpotsService.ChargingSpotsServiceImpl.internal_static_time_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ChargingSpotsService.ChargingSpotsServiceImpl.internal_static_time_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ChargingSpotsService.time.class, ChargingSpotsService.time.Builder.class);
  }

  public static final int TIMEON_FIELD_NUMBER = 1;
  private double timeOn_;
  /**
   * <code>double timeOn = 1;</code>
   */
  public double getTimeOn() {
    return timeOn_;
  }

  public static final int TIMEOFF_FIELD_NUMBER = 2;
  private double timeOff_;
  /**
   * <code>double timeOff = 2;</code>
   */
  public double getTimeOff() {
    return timeOff_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (timeOn_ != 0D) {
      output.writeDouble(1, timeOn_);
    }
    if (timeOff_ != 0D) {
      output.writeDouble(2, timeOff_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (timeOn_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, timeOn_);
    }
    if (timeOff_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, timeOff_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ChargingSpotsService.time)) {
      return super.equals(obj);
    }
    ChargingSpotsService.time other = (ChargingSpotsService.time) obj;

    boolean result = true;
    result = result && (
        java.lang.Double.doubleToLongBits(getTimeOn())
        == java.lang.Double.doubleToLongBits(
            other.getTimeOn()));
    result = result && (
        java.lang.Double.doubleToLongBits(getTimeOff())
        == java.lang.Double.doubleToLongBits(
            other.getTimeOff()));
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TIMEON_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getTimeOn()));
    hash = (37 * hash) + TIMEOFF_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getTimeOff()));
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ChargingSpotsService.time parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ChargingSpotsService.time parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ChargingSpotsService.time parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ChargingSpotsService.time parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ChargingSpotsService.time parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ChargingSpotsService.time parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ChargingSpotsService.time parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ChargingSpotsService.time parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ChargingSpotsService.time parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ChargingSpotsService.time parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ChargingSpotsService.time parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ChargingSpotsService.time parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ChargingSpotsService.time prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code time}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:time)
      ChargingSpotsService.timeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ChargingSpotsService.ChargingSpotsServiceImpl.internal_static_time_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ChargingSpotsService.ChargingSpotsServiceImpl.internal_static_time_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ChargingSpotsService.time.class, ChargingSpotsService.time.Builder.class);
    }

    // Construct using ChargingSpotsService.time.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      timeOn_ = 0D;

      timeOff_ = 0D;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ChargingSpotsService.ChargingSpotsServiceImpl.internal_static_time_descriptor;
    }

    @java.lang.Override
    public ChargingSpotsService.time getDefaultInstanceForType() {
      return ChargingSpotsService.time.getDefaultInstance();
    }

    @java.lang.Override
    public ChargingSpotsService.time build() {
      ChargingSpotsService.time result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ChargingSpotsService.time buildPartial() {
      ChargingSpotsService.time result = new ChargingSpotsService.time(this);
      result.timeOn_ = timeOn_;
      result.timeOff_ = timeOff_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ChargingSpotsService.time) {
        return mergeFrom((ChargingSpotsService.time)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ChargingSpotsService.time other) {
      if (other == ChargingSpotsService.time.getDefaultInstance()) return this;
      if (other.getTimeOn() != 0D) {
        setTimeOn(other.getTimeOn());
      }
      if (other.getTimeOff() != 0D) {
        setTimeOff(other.getTimeOff());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ChargingSpotsService.time parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ChargingSpotsService.time) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private double timeOn_ ;
    /**
     * <code>double timeOn = 1;</code>
     */
    public double getTimeOn() {
      return timeOn_;
    }
    /**
     * <code>double timeOn = 1;</code>
     */
    public Builder setTimeOn(double value) {
      
      timeOn_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double timeOn = 1;</code>
     */
    public Builder clearTimeOn() {
      
      timeOn_ = 0D;
      onChanged();
      return this;
    }

    private double timeOff_ ;
    /**
     * <code>double timeOff = 2;</code>
     */
    public double getTimeOff() {
      return timeOff_;
    }
    /**
     * <code>double timeOff = 2;</code>
     */
    public Builder setTimeOff(double value) {
      
      timeOff_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double timeOff = 2;</code>
     */
    public Builder clearTimeOff() {
      
      timeOff_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:time)
  }

  // @@protoc_insertion_point(class_scope:time)
  private static final ChargingSpotsService.time DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ChargingSpotsService.time();
  }

  public static ChargingSpotsService.time getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<time>
      PARSER = new com.google.protobuf.AbstractParser<time>() {
    @java.lang.Override
    public time parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new time(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<time> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<time> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ChargingSpotsService.time getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

