// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: report_problem.proto

package ReportProblemService;

public interface emptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:empty)
    com.google.protobuf.MessageOrBuilder {
}
