// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: report_problem.proto

package ReportProblemService;

public interface loginResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:loginResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string response = 1;</code>
   */
  java.lang.String getResponse();
  /**
   * <code>string response = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponseBytes();
}
