// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: report_problem.proto

package ReportProblemService;

public interface loginRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:loginRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string request = 1;</code>
   */
  java.lang.String getRequest();
  /**
   * <code>string request = 1;</code>
   */
  com.google.protobuf.ByteString
      getRequestBytes();
}
