// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: report_problem.proto

package ReportProblemService;

public interface problemFixesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:problemFixes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 number = 1;</code>
   */
  int getNumber();
}
