// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: report_problem.proto

package ReportProblemService;

public interface problemFixOrBuilder extends
    // @@protoc_insertion_point(interface_extends:problemFix)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string fix = 1;</code>
   */
  java.lang.String getFix();
  /**
   * <code>string fix = 1;</code>
   */
  com.google.protobuf.ByteString
      getFixBytes();
}
