// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: report_problem.proto

package ReportProblemService;

public final class ReportProblemServiceImpl {
  private ReportProblemServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_loginRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_loginRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_loginResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_loginResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_problemType_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_problemType_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_problemFixes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_problemFixes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_problemFix_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_problemFix_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_logoutRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_logoutRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024report_problem.proto\"\037\n\014loginRequest\022\017" +
      "\n\007request\030\001 \001(\t\"!\n\rloginResponse\022\020\n\010resp" +
      "onse\030\001 \001(\t\"\035\n\013problemType\022\016\n\006number\030\001 \001(" +
      "\005\"\036\n\014problemFixes\022\016\n\006number\030\001 \001(\005\"\031\n\npro" +
      "blemFix\022\013\n\003fix\030\001 \001(\t\" \n\rlogoutRequest\022\017\n" +
      "\007request\030\001 \001(\t\"\007\n\005empty2\306\001\n\024ReportProble" +
      "mService\022(\n\005Login\022\r.loginRequest\032\016.login" +
      "Response\"\000\0220\n\rReportProblem\022\014.problemTyp" +
      "e\032\r.problemFixes\"\0000\001\022.\n\rReportWarning\022\014." +
      "problemType\032\013.problemFix\"\000(\001\022\"\n\006LogOut\022\016" +
      ".logoutRequest\032\006.empty\"\000B2\n\024ReportProble" +
      "mServiceB\030ReportProblemServiceImplP\001b\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_loginRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_loginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_loginRequest_descriptor,
        new java.lang.String[] { "Request", });
    internal_static_loginResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_loginResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_loginResponse_descriptor,
        new java.lang.String[] { "Response", });
    internal_static_problemType_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_problemType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_problemType_descriptor,
        new java.lang.String[] { "Number", });
    internal_static_problemFixes_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_problemFixes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_problemFixes_descriptor,
        new java.lang.String[] { "Number", });
    internal_static_problemFix_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_problemFix_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_problemFix_descriptor,
        new java.lang.String[] { "Fix", });
    internal_static_logoutRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_logoutRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_logoutRequest_descriptor,
        new java.lang.String[] { "Request", });
    internal_static_empty_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
